Feature/array functions
manuelbarzi/skylab-bootcamp-201904 pull request #138
Opened 2019-04-11 07:13 UTC by carmecass

2019-04-11 07:42 UTC, paulusrex requested changes

2019-04-11 07:42 UTC, paulusrex commented on staff/carme-casserras/array-functions/concat.js
> +    var acum = array1;
Si lo haces de esta manera estás modificando el array1. Realmente copias la referencia del array, no su contenido. Necesitas copiar a un NUEVO array el array1, al igual que lo haces con el array2.

2019-04-11 07:42 UTC, paulusrex commented on staff/carme-casserras/array-functions/isArray.js
> +    if (!(array instanceof Array)) throw TypeError(array + ' is not an array')
Esta línea sobra. El objetivo de la función isArray es decir si algo es un array o no, por lo tanto no tiene sentido disparar un error si no lo es.

2019-04-11 07:42 UTC, paulusrex commented on staff/carme-casserras/array-functions/lastindexof.js
> +'user strict'
"use strict";

2019-04-11 07:42 UTC, paulusrex commented on staff/carme-casserras/array-functions/lastindexof.js
> +    for (var i = 0; i < array.length; i++) {
Deberías recorrer el array desde atrás hacía adelante. 
la fórmula normal es
for (var i = array.length -1; i >= 0; i--)

con esto lo recorres desde el último al primero

2019-04-11 07:42 UTC, paulusrex commented on staff/carme-casserras/array-functions/reduce.js
> +    var endAcum = 0;
te sobra endAcum, solo con el acum podrías hacerlo sin problemas

2019-04-22 10:26 UTC, lexbarba commented on staff/carme-casserras/safe-box/safe.box.test.js
> +'use strict';
@carmecass this file should not be in this PR!

2019-04-23 06:07 UTC, closed without merging